from _typeshed import SupportsLenAndGetItem
from collections.abc import Iterable, Iterator, Sequence
from types import TracebackType
from typing import Any, Protocol, TypeVar, overload

_T_co = TypeVar("_T_co", covariant=True)

class Row(Sequence[Any], SupportsLenAndGetItem[Any]):
    keys: Any
    def __getitem__(self, index: Any) -> Any: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __len__(self) -> int: ...

class Cursor:
    description: Any
    rowcount: int
    lastrowid: int
    arraysize: int
    connection: Connection
    def execute(self, sql: str, parameters: Iterable[Any] | None = None) -> Cursor: ...
    def executemany(self, sql: str, parameters: Iterable[Iterable[Any]]) -> Cursor: ...
    def fetchone(self) -> Row | None: ...
    def fetchmany(self, size: int = ...) -> list[Row]: ...
    def fetchall(self) -> list[Row]: ...
    def close(self) -> None: ...
    def __iter__(self) -> Iterator[Row]: ...
    def __enter__(self) -> Cursor: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None) -> None: ...

class Connection:
    row_factory: Any
    text_factory: Any
    total_changes: int
    in_transaction: bool
    def cursor(self) -> Cursor: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...
    def execute(self, sql: str, parameters: Iterable[Any] | None = None) -> Cursor: ...
    def executemany(self, sql: str, parameters: Iterable[Iterable[Any]]) -> Cursor: ...
    def executescript(self, sql_script: str) -> Cursor: ...
    def create_function(self, name: str, num_params: int, func: Any) -> None: ...
    def __enter__(self) -> Connection: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None) -> None: ...

def connect(database: str, timeout: float = ..., detect_types: int = ..., isolation_level: str | None = ..., check_same_thread: bool = ..., factory: type[Connection] | None = ..., cached_statements: int = ...) -> Connection: ...
