PidFile /var/run/opendkim/opendkim.pid
Mode sv
Socket inet:8891@0.0.0.0
Umask 002
SendReports yes
SoftwareHeader yes
Canonicalization relaxed/relaxed
Selector default
InternalHosts refile:/etc/opendkim/trusted-hosts
SigningTable refile:/etc/opendkim/signing-table
KeyTable refile:/etc/opendkim/key-table

Syslog no
LogWhy yes

OversignHeaders From
RequireSafeKeys no
