from __future__ import annotations

from typing import Any, Protocol


class MailServerProvider(Protocol):
    def add_domain(self, domain: str) -> dict[str, Any]: ...
    def remove_domain(self, domain: str) -> dict[str, Any]: ...
    def add_user(self, email: str, password: str, quota_bytes: int | None = None) -> dict[str, Any]: ...
    def remove_user(self, email: str) -> dict[str, Any]: ...
    def set_password(self, email: str, password: str) -> dict[str, Any]: ...
    def set_quota(self, email: str, quota_bytes: int) -> dict[str, Any]: ...
    def set_sending_limit(self, email: str, max_per_day: int) -> dict[str, Any]: ...
    def delete_sending_limit(self, email: str) -> dict[str, Any]: ...
    def check_user(self, email: str) -> bool: ...
    def list_users(self, domain: str = "") -> list[dict[str, Any]]: ...
    def is_available(self) -> bool: ...
    def generate_dkim_key(self, domain: str, selector: str | None = None) -> dict[str, Any]: ...
    def get_dkim_key(self, domain: str, selector: str | None = None) -> dict[str, Any]: ...
    def remove_dkim_key(self, domain: str, selector: str | None = None) -> dict[str, Any]: ...
